# Generated by Django 2.1.4 on 2019-01-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
