# Generated by Django 2.1.4 on 2019-01-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='active_ind',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
