# Generated by Django 2.1.4 on 2019-01-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20190118_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_ins_ts', models.DateTimeField()),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('num_workouts', models.IntegerField(default=0)),
                ('total_time', models.DateTimeField()),
            ],
        ),
    ]
