# Generated by Django 2.1.4 on 2019-01-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nm', models.CharField(max_length=200)),
                ('last_nm', models.CharField(max_length=200)),
                ('email_addr_txt', models.CharField(max_length=200)),
                ('rec_ins_ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Gym')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='sets',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sets',
            name='session',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='workouts.Session'),
        ),
    ]
