# Generated by Django 2.1.4 on 2019-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_summaryindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_open',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
