# Generated by Django 2.1.4 on 2019-01-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20190106_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Gym'),
        ),
    ]
