# Generated by Django 2.1.4 on 2019-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20190106_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sets',
            new_name='Set',
        ),
    ]
