# Generated by Django 2.1.4 on 2019-02-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_session_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_order_nbr', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_nm', models.CharField(max_length=200)),
                ('rec_ins_ts', models.DateTimeField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='plannedsets',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Program'),
        ),
    ]
