# Generated by Django 2.1.4 on 2019-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20190106_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='email_addr_txt',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='first_nm',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='last_nm',
        ),
        migrations.AddField(
            model_name='individual',
            name='user_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
