# Generated by Django 2.1.4 on 2019-02-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20190202_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedsets',
            name='num_sets',
            field=models.IntegerField(default=1),
        ),
    ]
